# Global variables
PROJECT_NAME         = Flame
PROJECT_VERSION      = 0.1.0
PROJECT_DESCRIPTION  = Graphical user interface for exploring Mandelbrot and Julia fractals
PROJECT_AUTHORS      = Nicolas Lermé
