# Global variables
PROJECT_NAME         = Fraktal
PROJECT_VERSION      = 1.0.0
PROJECT_DESCRIPTION  = tool for drawing fractals
PROJECT_AUTHORS      = Nicolas Lerme (nicolas.lerme@free.fr)
PROJECT_LAST_RELEASE = `date`
